# Generated by Django 4.2.16 on 2024-10-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Employee's full name", max_length=100)),
                ('city', models.CharField(help_text='City', max_length=50)),
                ('contact', models.CharField(help_text='Contact number', max_length=15)),
                ('email', models.EmailField(help_text='Email Address', max_length=254)),
            ],
        ),
    ]
